### PR TITLE
Rename generic-dependence.pdf to generic-dependence.pdf 

### PR DESCRIPTION
**Pull request by CarterBeauBenson**

### CODE REVIEW

**Comment by alanruttenberg** [comment]
What did this patch do? I reads as changing the file name to what it was before.

**Comment by alanruttenberg** [comment]
Also the parent directory should be pdf, not pds

**Comment by CarterBeauBenson** [comment]
It was a mistake. I was trying to fix a minor typo in the file. I didn’t
mean to create a pull request once I couldn’t edit the PDF. My apologies.

**Comment by alanruttenberg** [comment]
np. Will close.

**Pull request closed without merging**
